# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f5f37193692d98ee1ab10427cf79ea9ab4238be2d1496b166fc4a63bcfb2edf054942ab74fa238e3b37e8f4867103c90d516c29fa270599aa5773330f5c50ed8

test:
  secret_key_base: b5e35dffca6da961b16f019cec94745607ff013e0d26dadce06a5491ae814bcdf733589bb1f63c68ad2ab20d9403a4f52458eb339dce6cd0d51726242b08992e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
